all:
  hosts:
    dev_vm:
      ansible_host: 192.168.56.10
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/default/virtualbox/private_key
      ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
